### ISSUE TITLE
Added new method isOngoing (TV Series)

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#11]
This indicates if a tv series is still running or ended

Returns:
false (tv series has ended)
true (tv series is still running)
Null (not a tv series)

Check it out if you like

**Comment by duck7000** [comment]
Is this something anyone is going to use?
I'm not but it might be of any interest.

If not i probably will remove it

**Comment by duck7000** [comment]
Closing this one, nobody seems interested, including me.

For now i will leave it in, doesn't hurt

**Comment by duck7000** [comment]
I'm going to remove this method, there is no interest, by me or others.
And the method can have 3 different output values that can't be with boolean..

**Comment by mosource21** [comment]
In the future if I ever used the library for TV Series I would probably like to know the Ongoing status but I have no immediate need.

<ins>Option 1</ins>
false (tv series has ended / not a tv series)
true (tv series is still running)
(keep things simple you will be checking movietype to see if it is a tv series or not)

<ins>Option 2 (your original plan)</ins>
false (tv series has ended)
true (tv series is still running)
Null (not a tv series)

Either option would work with something like the following when in use:

`if (!empty(ongoing)) {`
` //ongoing tv series`
`}`

**Comment by duck7000** [comment]
Thanks for your comments!

I checked what imdb does at GraphQL:

false: tv series has ended
true: still running tv serie
null: no tv series, no value

So what i originally did is correct (imdb does the same), although it is not type correct (boolean can not be anything else then true or false) but it seems the best option, agree?

If so i will restore this method as it might be useful in the future

**Comment by duck7000** [comment]
i re added it in the latest git commit

**Comment by mosource21** [comment]
>So what i originally did is correct (imdb does the same), 
>but it seems the best option, agree?

I am torn and see positives and negatives for several different solutions.  
However, why make things difficult IMDB must have done it that way for a reason so it probably is the best option.

>although it is not type correct (boolean can not be anything else then true or false)

I will be somewhat refuting this and making a few other points in the https://github.com/duck7000/imdbGraphQLPHP/issues/80 thread soon.

>If so i will restore this method as it might be useful in the future

👍

**Comment by duck7000** [comment]
This is re added so closing this one
