### ISSUE TITLE
Name class spouse() changes!

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#111]
I changed comments to array as there might be more than one comment.
Nobody ever noticed this before but this might be a wise move

**Comment by GeorgeFive** [comment]
Do you have an example of a person with more than one comment for my own testing?

**Comment by duck7000** [comment]
No, i went through the code and noticed that comments are appended to each other if there are more than one, so that can't be right.

It probably never occurred that there are more than one comment as nobody, including me, me noticed this before
