### ISSUE TITLE
Missing use Psr\Log\LoggerInterface; in Title class

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#113]
`use Psr\Log\LoggerInterface;` is missing in Title class

**Comment by duck7000** [comment]
That might not be necessary as Title is a extention of mdbBase class?

Does logger work or not?

I can add it anyway, i included it in Name class so this might confusing
Okay i will add it

**Comment by duck7000** [comment]
It is added in latest commit

**Comment by jcvignoli** [comment]
I haven't reached yet the step where I can confirm whether the logger works, but Title class wasn't indeed able to find LoggerInterface.
Thanks for the commit!
