### ISSUE TITLE
Slow query

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#116]
I noticed that for some queries the time to get the information is extremely slow.

An exemple : "game of thrones"

I'm doing the query with "MOVIE,TV" with "EN" country.  The cache is active, but for that particular movie, it's very slow.

**Comment by duck7000** [comment]
Mm i need more info

I assume you mean TitleSearch class with "MOVIE,TV" and country set in config to "EN"?
Then it is extremely slow with game of thrones as search string, correct?

Okay i will test this here in the Netherlands

**Comment by duck7000** [comment]
For country i assume you are talking about this config setting:
$country = "DE";?

Did you read the doc block that is on top of that setting? Only the country's listed are working..
Imdb only support those country's or default to US

**Comment by duck7000** [comment]
If you are talking about TitleSearchAdvanced then i have to check which country's are supported

**Comment by jcvignoli** [comment]
Sorry, it's "US" I'm using. Please note this happens with a few movies only so far, so this is not related to an option, I use the same options everywhere. Trying to find a pattern, but could related to "TV" category, I don't have enough info yet.
For "2001" (which return the movie 2001 a space odyssey) it's fast. For "game of thrones", very slow.

I'm using TitleSearch class.

**Comment by duck7000** [comment]
You don't have to use US for $country in config, it defaults to US if you disable localization
US is not in the supported country's list so this might be why it is slow?

**Comment by jcvignoli** [comment]
It works perfectly with other movie's names. Have you tried to search for "game of thrones"? Is it fast compared to "2001"?

**Comment by duck7000** [comment]
yes for both titles, it works instantly, less than one second

With localization disabled so it defaults to US

Localization is only to get the country local name for example title name. It has nothing to do with searching in US only

It might be that imdb servers are slow in your country?

**Comment by jcvignoli** [comment]
No, something else is happening, which therefore is related to my use of your library since you can't reproduce. I need to investigate more.

What I tried:
1/ Remove localisation/ localisation on => same issue
a/ Searching "games of thrones" => extremely slow, 3-5 minutes of waiting (with or without localisation)
b/ Searching "2001" => fast (with or without localisation)

I will run further tests.

**Comment by GeorgeFive** [comment]
Are you perhaps getting additional info for the titles in the search results?  The code I use to work with this class has three options:

1. Title search only, will find "Game of Thrones" as a title, instant results.
2. Episode search, will find "Game of Thrones" and all episodes tied to it, takes about 30 seconds.
3. Full search, will find "Game of Thrones", all episodes, and all credits for each episode... this will take 3-5 minutes as you mentioned.

**Comment by jcvignoli** [comment]
Thanks @GeorgeFive, was actually to do that once I finished the integration.

I actually found the issue: the trailer() method in Title class.
1/ No matter the vars trailer(0), trailer(0, false), trailer(1), the method is extreeeemly slow.
2/ Game of thrones has over 300 videos https://www.imdb.com/title/tt0944947/videogallery/?ref_=ttvg
3/ Unless I'm mistaken, the method parses all videos.

Suggestion: Why no limit the number of videos parsed to the int passed in $amount?

**Comment by duck7000** [comment]
Mm it is getting better and better
What has this to do with a search if i may ask? If you like your suggestion use the search as a Title object and include all methods then yes i understand it is slow as hell..

first of all trailer method parses trailers until it finds one (yes the default is only one) that can/may be embedded in a iframe tag (not all imdb trailers do!)
So if this is extremely slow means that there probably is no trailer to be found that can be embedded i assume?

I don't know up front how many trailers i need to check to find one that can be embedded so i can't set a limit up front.

In my program i want to be able to embed a trailer in a iframe tag, otherwise the url will not be playable inside my program

I don't know how you are using those trailers?

So I'm open to suggestions!

**Comment by jcvignoli** [comment]
>What has this to do with a search if i may ask? If you like your suggestion use the search as a Title object and include all methods then yes i understand it is slow as hell..

The only method that slows the process is trailer(), I don't understand your response. Other methods are fast.

> So if this is extremely slow means that there probably is no trailer to be found that can be embedded i assume?

Test it yourself! ;) Get the trailers for "game of thrones" using Title::trailer(). In my tests, it returns an array of 10 rows.

```
array(10) { [0]=> array(7) { ["name"]=> string(23) "Official Series Trailer" ["runtime"]=> int(199) ["description"]=> string(34) "It’s time to return to Westeros." ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(53) "https://www.imdb.com/video/imdb/vi59490329/imdb/embed" ["videoImageUrl"]=> string(162) "https://m.media-amazon.com/images/M/MV5BZTg4YzdjNTctNDg5Mi00ZmU1LTkzOWEtNmMyNDBjZjNhNTJiXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [1]=> array(7) { ["name"]=> string(27) "Season 8, Episode 5 Preview" ["runtime"]=> int(40) ["description"]=> string(67) "Watch the trailer for the penultimate episode of "Game of Thrones."" ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(55) "https://www.imdb.com/video/imdb/vi1509866521/imdb/embed" ["videoImageUrl"]=> string(142) "https://m.media-amazon.com/images/M/MV5BMTYyYWNkMTYtOTQxNS00NDI0LWFlNTgtNmJhNjUyN2IxNmNlXkEyXkFqcGdeQWFybm8@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [2]=> array(7) { ["name"]=> string(26) "Season 8 Episode 4 Trailer" ["runtime"]=> int(31) ["description"]=> string(29) "Now we will win the Last War." ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(55) "https://www.imdb.com/video/imdb/vi1911798809/imdb/embed" ["videoImageUrl"]=> string(146) "https://m.media-amazon.com/images/M/MV5BZjhmZjk2YzItOGEwNS00YWEzLThjNjUtOTNkNDE5NzZmZmY5XkEyXkFqcGdeQW1yb3NzZXI@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [3]=> array(7) { ["name"]=> string(26) "Season 8 Episode 3 Trailer" ["runtime"]=> int(32) ["description"]=> string(87) "The Night King and his army have arrived at the Winterfell and the great battle begins." ["titleName"]=> string(14) "The Long Night" ["titleYear"]=> int(2019) ["videoUrl"]=> string(55) "https://www.imdb.com/video/imdb/vi2409413657/imdb/embed" ["videoImageUrl"]=> string(146) "https://m.media-amazon.com/images/M/MV5BZGY3NTY0MTQtMjBlYi00Zjc0LTgzZDctZWUwNTk1MTE5OWI1XkEyXkFqcGdeQXRzdGFzaWVr._V1_QL75_UX500_CR0,0,500,281_.jpg" } [4]=> array(7) { ["name"]=> string(44) ""Game of Thrones" Season 8 Episode 2 Trailer" ["runtime"]=> int(40) ["description"]=> string(151) "The battle at Winterfell is approaching. Jaime is confronted with the consequences of the past. A tense interaction between Sansa and Daenerys follows." ["titleName"]=> string(30) "A Knight of the Seven Kingdoms" ["titleYear"]=> int(2019) ["videoUrl"]=> string(55) "https://www.imdb.com/video/imdb/vi2003090713/imdb/embed" ["videoImageUrl"]=> string(162) "https://m.media-amazon.com/images/M/MV5BZmEyODRlZjctMTE3Yi00MGRlLWFhNDctMGJmZmUzOGVmYjExXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [5]=> array(7) { ["name"]=> string(26) "Season 8 Promo "Aftermath"" ["runtime"]=> int(62) ["description"]=> string(56) "Promo trailer for the final season of "Game of Thrones."" ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(55) "https://www.imdb.com/video/imdb/vi3521494297/imdb/embed" ["videoImageUrl"]=> string(162) "https://m.media-amazon.com/images/M/MV5BZWI3MmVjNTUtYzI4Yy00ZmIwLWE0ZDQtNTMyOTYxZWE3MGM5XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [6]=> array(7) { ["name"]=> string(26) "Season 8 Promo: "Together"" ["runtime"]=> int(31) ["description"]=> string(56) "Promo trailer for the final season of "Game of Thrones."" ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(54) "https://www.imdb.com/video/imdb/vi618970393/imdb/embed" ["videoImageUrl"]=> string(146) "https://m.media-amazon.com/images/M/MV5BYzQ5NWFmNWItMDkyMC00YzU1LWI2MTQtYWQ0YjEyYmNjNjdiXkEyXkFqcGdeQW1yb3NzZXI@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [7]=> array(7) { ["name"]=> string(26) "Season 8 Promo: "Survival"" ["runtime"]=> int(31) ["description"]=> string(56) "Promo trailer for the final season of "Game of Thrones."" ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(54) "https://www.imdb.com/video/imdb/vi585415961/imdb/embed" ["videoImageUrl"]=> string(162) "https://m.media-amazon.com/images/M/MV5BMTEyMmQyOTktNDRlNC00NTJjLWEzODItMWU0Y2U4YzJmZDBlXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [8]=> array(7) { ["name"]=> string(25) "Season 8 Official Trailer" ["runtime"]=> int(113) ["description"]=> string(60) "Watch the trailer for the final season of "Game of Thrones."" ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(55) "https://www.imdb.com/video/imdb/vi3191978521/imdb/embed" ["videoImageUrl"]=> string(146) "https://m.media-amazon.com/images/M/MV5BMTg4ZTA4YzgtZGQ1YS00YTEyLTgwM2UtNzIwNGY0MjQ4YjgxXkEyXkFqcGdeQW1yb3NzZXI@._V1_QL75_UX500_CR0,0,500,281_.jpg" } [9]=> array(7) { ["name"]=> string(40) ""Crypts of Winterfell" - Season 8 Teaser" ["runtime"]=> int(90) ["description"]=> string(65) "Watch a teaser trailer for the final season of "Game of Thrones."" ["titleName"]=> string(15) "Game of Thrones" ["titleYear"]=> int(2011) ["videoUrl"]=> string(55) "https://www.imdb.com/video/imdb/vi4279613977/imdb/embed" ["videoImageUrl"]=> string(146) "https://m.media-amazon.com/images/M/MV5BNTNmOTkyZjgtZWUxNC00NzQzLWE5ODQtMTliMGYyNzVkNjM3XkEyXkFqcGdeQW1yb3NzZXI@._V1_QL75_UX500_CR0,0,500,281_.jpg" } }
```

Please also note that `Title::trailer()` can throw errors if it fails to get the URL:

```
Warning: get_headers(https://www.imdb.com/video/imdb/vi4115117337/imdb/embed): Failed to open stream: HTTP request failed! in /dist/vendor/duck7000/imdb-graphql-php/src/Imdb/Title.php on line 2115

Warning: Trying to access array offset on false in /dist/vendor/duck7000/imdb-graphql-php/src/Imdb/Title.php on line 2116

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /dist/vendor/duck7000/imdb-graphql-php/src/Imdb/Title.php on line 2116
```
I believe you should validate the array before using substr() on line 2116:

`if (substr($headers[0], 9, 3) == "404" || substr($headers[0], 9, 3) == "401") {`

>I don't know how you are using those trailers?

I'm using the trailer() method to get the IMDb URL.

>So I'm open to suggestions!

I can't think of any elegant way to speed up the process. You have to check hundreds of links, depening on the movies.

Now I understand how the function works, I will unfortunately myself stop using it, since I believe it's unethical to query hundreds of IMDb's URL to find a relevant data. I try to minimize my impact on IMDb.

But should you want me to test the method later on, I will be happy to do so!

**Comment by duck7000** [comment]
> > I don't know how you are using those trailers?
> 
> I'm using the trailer() method to get the IMDb URL.

I mean what do you do with the result of trailer method? use it to play in a browser, save the trailer etc.

**Comment by duck7000** [comment]
> I will unfortunately myself stop using it, since I believe it's unethical to query hundreds of IMDb's URL to find a relevant data

This is not true, the method gets all trailer url's in one query, then checks those trailer urls through a header method, nothing unethical to me?

**Comment by duck7000** [comment]
> Test it yourself! ;) Get the trailers for "game of thrones" using Title::trailer(). In my tests, it returns an array of 10 rows.

This cannot be!
If i do the same i get one result (as the default is one)
But indeed it is slow!

```
Array
(
    [0] => Array
        (
            [name] => Official Series Trailer
            [runtime] => 199
            [description] => It’s time to return to Westeros.
            [titleName] => Game of Thrones
            [titleYear] => 2011
            [videoUrl] => https://www.imdb.com/video/imdb/vi59490329/imdb/embed
            [videoImageUrl] => https://m.media-amazon.com/images/M/MV5BZTg4YzdjNTctNDg5Mi00ZmU1LTkzOWEtNmMyNDBjZjNhNTJiXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_1_SP330,330,0,C,0,0,0_CR65,90,200,150_PIimdb-blackband-204-14,TopLeft,0,0_PIimdb-blackband-204-28,BottomLeft,0,1_CR0,0,200,150_PIimdb-bluebutton-big,BottomRight,-1,-1_ZATrailer,4,123,16,196,verdenab,8,255,255,255,1_ZAon%2520IMDb,4,1,14,196,verdenab,7,255,255,255,1_ZA03%253A19,164,1,14,36,verdenab,7,255,255,255,1_ZAGame%2520of%2520Thrones,4,138,14,176,arialbd,7,255,255,255,1_.jpg
        )

)
/
```

**Comment by duck7000** [comment]
> Please also note that `Title::trailer()` can throw errors if it fails to get the URL:
> 
> ```
> Warning: get_headers(https://www.imdb.com/video/imdb/vi4115117337/imdb/embed): Failed to open stream: HTTP request failed! in /dist/vendor/duck7000/imdb-graphql-php/src/Imdb/Title.php on line 2115
> 
> Warning: Trying to access array offset on false in /dist/vendor/duck7000/imdb-graphql-php/src/Imdb/Title.php on line 2116
> 
> Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /dist/vendor/duck7000/imdb-graphql-php/src/Imdb/Title.php on line 2116
> ```
> 
> I believe you should validate the array before using substr() on line 2116:
> 
> `if (substr($headers[0], 9, 3) == "404" || substr($headers[0], 9, 3) == "401") {`

This is fixed in latest commit
But yes get_headers makes it slow with 300 urls, i can't do anything about that.

The only thing i can do is make a separate trailer method that spits out the first trailer url it founds with a config setting for how many urls you want?
In the wiki is it mentioned that urls are validated to be able to embed them

**Comment by duck7000** [comment]
Or use the video() method, that one has no restrictions, it simply returns all urls it finds in a categorized array.
Would be a lot faster

**Comment by jcvignoli** [comment]
The video() method works perfectly and is fast, thanks!

I close the issue.

**Comment by duck7000** [comment]
The video() method returns imdb video urls as is and those urls only work in a browser
Embedding or use it in a html video tag is not working.

I added the video method just to get all videos as trailer() is specifically checked to be able to embed it in a iframe.
That check will make it slow with 300 urls though
I will make that more clear in the wiki
