### ISSUE TITLE
TitleSearch searchObject()?

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#118]
I'm wondering whether a previous search method that returns a Title object could be implemented.

Rational: the TitleSearch class returns only a bunch of data (title, titleOriginal, imdbid, year and movieType). It's a small drop of all data included in Title class. It may be useful for devs a search method that returns a Title object instead of those 5 data.

Changes: I limited the changes to add two methods. One in TitleSearch and one in Title.  The search() method in TitleSearch could be further factorized with the new searchObject() method, so both methods could use the same $query var (easier maintainibility).

1/ TitleSearch, adding a method searchObject()

2/ Title, new method fromSearchResult(), basically the same method from IMDbPHP with an extra variable (original title) to ensure compatiblity with TitleSearch::searchObject() method

**Edit: removed the methods, made a pull. Hope it is correct.**

**Comment by duck7000** [comment]
Well.. i didn't understand why this was in imdbphp as it is pointless to the way i use this library.
And i certainly still don't understand why i should implant it now.

In my opinion search() is used to find titles which include the search string, pick the one you want and use the title id to get all info you want through the Tittle class.

I don't see the point of doing that twice? I mean Title object that you want returns the same data, be it in a object instead of array()

And i see debug entrys added in cache? Don't mix up pull requests with debug entrys please

**Comment by jcvignoli** [comment]
I'll reply re: the cache in the [cache issue](https://github.com/duck7000/imdbGraphQLPHP/issues/117).

1/ Sorry for the multiple pulls (and mix with Cache and Exception class). First time using this. I'm struggling to understand the branches and all those things. Was trying to separate the pulls by issues, didn't find how to do it.

2/ I would prefer to also have one method in TitleSearch that returns the Title class only, but I guess for compatilibilty with the current imdbGraphQLPHP users, would be better to have two methods.

3/ This is not a duplication: the current way returns limited info. The proposal (copied from IMDBphp) offers a huge number of methods that can be called in Title class. You basically offer 5 fields, Title class has something like 20 methods that can return information.

4/ I understand your view of what the search is. But think about the devs: they need to access much more than those 5 fields (4 actually, two are titles). The current behaviour may feet your needs. The old behaviour feets everybody needs, and doesn't cost anything in terms of maintainibilty (if 3 methods are created in TitleSearch)

**Comment by duck7000** [comment]
I understand your point of view too.

But i still don't see why a search would have to have all possible fields from Title class? I mean if you want that call the title class with the id and get all you want, in other words i don't see the relation between those 2?

I can of course include every possible data in the search results itself but that would be a huge amount of data to, in my case, only get the title and id

And your proposal includes the same info as the search results? Only difference is that it would be a object instead of array()? This is at least how i see it.
This function get info from search results as parameters, creates a new instance of the Title class and sets protected vars from Title class to the parameters data.
so it only creates a object with data from search results?

And that Title class should return  the data from a TitleSearch feels wrong to me, TitleSearch is not Title class info in my view

```
    public static function fromSearchResult(
        $id,
        $title,
        $year,
        $type,
        Config $config = null,
        LoggerInterface $logger = null,
        CacheInterface $cache = null
    ) {
        $imdb = new Title($id, $config, $logger, $cache);
        $imdb->main_title = $title;
        $imdb->main_year = (int)$year;
        $imdb->main_movietype = $type;
        return $imdb;
    }
```

And if i do implant what you are asking i have to do it the same in all other search class to make everything the same

**Comment by jcvignoli** [comment]
> But i still don't see why a search would have to have all possible fields from Title class? I mean if you want that call the title class with the id and get all you want, in other words i don't see the relation between those 2?

Gonna clarify this. Once the movie's title is found using TitleSearch, I can get the sound(), the director() (especially the director!) etc directly from Title, using the result of TitleSearch. Otherwise, TitleSearch gets only the array of the four vars in TitleSearch::search().

In other words, it's more maintainable and faster.

>I can of course include every possible data in the search results itself but that would be a huge amount of data to, in my case, only get the title and id

Indeed. That's why the IMDbPHP method is easier to implement.

> And your proposal includes the same info as the search results? Only difference is that it would be a object instead of array()? This is at least how i see it.

That's the whole point. Instead of getting an array of 4 vars, I get an object I can query which gives me access to all methods available in Title.

> And that Title class should return the data from a TitleSearch feels wrong to me, TitleSearch is not Title class info in my view

I don't understand. This is [OOP](https://en.wikipedia.org/wiki/Object-oriented_programming) coding. It's meant to increase maintainability.

> And if i do implant what you are asking i have to do it the same in all other search class to make everything the same

I guess it would be great, like putting in Name class. I don't use the other classes like Keywords, Chart, Company, so I don't know how useful it may be.

Hope I clarified a bit.

**Comment by duck7000** [comment]
Ooh.. i think i understand a little bit about this..

The whole point is to have access to Title class methods directly from the search results, correct?
Well this is certainly and totally not my use case but i'm getting a little bit why it might be important to others
So now you get my concerns about this as i didn't understand other use cases of this library

@GeorgeFive what is your take about this?
So alright it is important enough to think about, agree?
The question is what the best approach is, i do not like the possibility of 2 search methods so we might consider to implant this in the existing search method (and the function in Title class)
The only difference for me would be return value been array versus object so technically i can live with that

Well the only thing i know about OOP is what is inside this project.. so yes sometimes i need teaching

**Comment by GeorgeFive** [comment]
I'm going to stay neutral on this.  I don't think it's a horrible idea, and I could see the benefit for some users, but on the flip side, I personally wouldn't be using it.  In the few use cases where I need extra data, I just do another foreach and run it through like that... and then cache the data, so I only need to do it once.

**Comment by jcvignoli** [comment]
> The whole point is to have access to Title class methods directly from the search results, correct?

Exactly.

> So now you get my concerns about this as i didn't understand other use cases of this library

I totally understand.

> The question is what the best approach is, i do not like the possibility of 2 search methods so we might consider to implant this in the existing search method (and the function in Title class)

A more elegant way would be indeed to pass a given argument in the method. Using bool (true or false) is [deeply discouraged in OOP coding](https://understandlegacycode.com/blog/what-is-wrong-with-boolean-parameters/#:~:text=%E2%80%9CBoolean%20arguments%20loudly%20declare%20that,confusing%20and%20should%20be%20eliminated.%E2%80%9D&text=If%20the%20function%20does%20more,they%20all%20do%20one%20thing.). 

Suggestions:
1/ You can add the Title object inside the array, such as in
```
            $results[] = array(
                'imdbid' => isset($edge->node->entity->id) ?
                                  str_replace('tt', '', $edge->node->entity->id) : null,
                'title' => isset($edge->node->entity->titleText->text) ?
                                 $edge->node->entity->titleText->text : null,
                'originalTitle' => isset($edge->node->entity->originalTitleText->text) ?
                                         $edge->node->entity->originalTitleText->text : null,
                'year' => $yearRange,
                'movietype' => isset($edge->node->entity->titleType->text) ?
                                     $edge->node->entity->titleType->text : null,
                'titleSearch' => Title::fromSearchResult(
                     isset($edge->node->entity->id) ? str_replace('tt', '', $edge->node->entity->id) : null, // IMDb ID.
                     isset($edge->node->entity->titleText->text) ? $edge->node->entity->titleText->text : null, // Title.
                     isset($edge->node->entity->originalTitleText->text) ? $edge->node->entity->originalTitleText->text : null, // Original title.
                     $yearRange, // Year.
                     isset($edge->node->entity->titleType->text) ? $edge->node->entity->titleType->text : null, // Movie type.
                     $this->config,
                     $this->logger,
                     $this->cache
                 );
            );
```
2/ Or easier method, add an extra method that gets Title::fromSearchResults

```
            $imdb_id = isset($edge->node->entity->id) ?
                                  str_replace('tt', '', $edge->node->entity->id) : null;
            (etc)
            $results[] = array(
                'imdbid' =>  $imdb_id,
                (etc),
                'titleSearch' => $this->getObject( $imdb_id, (etc) )
            );

function getObject( 
       return Title::fromSearchResult(
              $imdb_id, (etc) 
      );
);
```
It could then be called
```
$search = TitleSearch::search();
$search['titleSearch']->director();
```

if I'm correct.

I'm still in the learning process of OOP, so I'm afraid I can't think of much better. There are other solutions I guess, that would allow to call the method like in TitleSearch::search()->object(), but I don't know yet how to do.

**Comment by duck7000** [comment]
> A more elegant way would be indeed to pass a given argument in the method. But using bool (true or false) is [deeply discouraged in OOP coding](https://understandlegacycode.com/blog/what-is-wrong-with-boolean-parameters/#:~:text=%E2%80%9CBoolean%20arguments%20loudly%20declare%20that,confusing%20and%20should%20be%20eliminated.%E2%80%9D&text=If%20the%20function%20does%20more,they%20all%20do%20one%20thing.).

Interesting, but this is about javascript but i get the idea. In principle is use boolean only when i need 2 choices, if i need a third or more i change to a different method like a variable with different values

**Comment by duck7000** [comment]
now that i think about it your problem with trailer() is a downside if you use title object from search results?
just a thought though

**Comment by duck7000** [comment]
I'll think about it how to neatly implant this

**Comment by duck7000** [comment]
> I'm going to stay neutral on this. I don't think it's a horrible idea, and I could see the benefit for some users, but on the flip side, I personally wouldn't be using it. In the few use cases where I need extra data, I just do another foreach and run it through like that... and then cache the data, so I only need to do it once.

Well i'm in the same boat, i do understand now this is important to other use cases but personally i wouldn't use it either.
So we have to think of a smart some kind of switch, parameter or something

**Comment by jcvignoli** [comment]
>Interesting, but this is about javascript but i get the idea. In principle is use boolean only when i need 2 choices, if i need a third or more i change to a different method like a variable with different values

javascript or php, same issues. I found [a better explaination](https://medium.com/@MaLiN2223/my-boolean-vendetta-a2b473a64830), much clearer, if it's of interest to you.

> now that i think about it your problem with trailer() is a downside if you use title object from search results?
just a thought though

It wouldn't make any difference.

> Well i'm in the same boat, i do understand now this is important to other use cases but personally i wouldn't use it either.
So we have to think of a smart some kind of switch, parameter or something

The latest suggestions have the advantage to not require any change by end users, since it's just a new row is created in the returned array. A new argument to TitleSearch::search(), even if set by default on boolean, may always have side effects. Especially if you add later on new arguments that have no default value.

I have hundred of classes in a few projects, so I'm obsessed by maintainability, the less I change the arguments, the happier I am  ;)

**Comment by duck7000** [comment]
I'm more thinking of a extra parameter in search() method, if you want a Title Object or array as return?
There won't come any other parameters as there are no more options left in GraphQL API
Or a config setting might even better, set it there what you want

That way i can add a if statement which separate the 2 return options

Default it will remain like it is now though, so @jcvignoli would need to change that setting.

This has advantages, the TitleSearch class code doesn't need to be changed much and it will only effect those how need/want it

**Comment by duck7000** [comment]
I come up with this, it is only a part of titleSearch search() just to show how i thought about it. Tested and works great for both cases!
var $returnType is set in config, an extra parameter might be confusing to what it is for

```
            $id = isset($edge->node->entity->id) ?
                        str_replace('tt', '', $edge->node->entity->id) : null;
            $title = isset($edge->node->entity->titleText->text) ?
                           $edge->node->entity->titleText->text : null;
            $origTitle = isset($edge->node->entity->originalTitleText->text) ?
                               $edge->node->entity->originalTitleText->text : null;
            $movieType = isset($edge->node->entity->titleType->text) ?
                               $edge->node->entity->titleType->text : null;
            if ($returnType == 'array') {
                $return = array(
                    'imdbid' => $id,
                    'title' => $title,
                    'originalTitle' => $origTitle,
                    'year' => $yearRange,
                    'movietype' => $movieType
                );
            } else {
                $return = Title::fromSearchResult(
                    $id,
                    $title,
                    $origTitle,
                    $yearRange,
                    $movieType,
                    $this->config,
                    $this->logger,
                    $this->cache
                );
            }
            $results[] = $return;
        }
        return $results;
```

**Comment by jcvignoli** [comment]
That's up to you. Looking forward to testing your solution!

**Comment by duck7000** [comment]
I decided to implant the first idea of @jcvignoli so i added it as a extra element in $results

It is a simple code change, easy to understand and for existing users it all stays the same.
For users who do want to use the Title Object approach they can use the extra array element to get the object

I tested this and works great but do test it yourself

I am thinking/not sure to implant this in nameSearch class as probably nobody uses that class. I added it for completeness sake just like the other classes

**Comment by jcvignoli** [comment]
> I tested this and works great but do test it yourself

Done, it works great!

Thank you so much. I'll see how can I test the NameSearch class, I haven't any use right now.

But this is great!
