### ISSUE TITLE
Undefined variable $results in Name class

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#120]
Method pubinterview() in Name class is incorrectly coded. A var declaration is missing for $results

Replace
```
    public function pubinterview()
    {
        if (empty($this->pubInterview)) {
            $results = $this->pubOtherListing("PublicityInterview");
        }
        $this->pubInterview = $results;
        return $this->pubInterview;
    }
```
by

```
    public function pubinterview()
    {
        $results = '';
        if (empty($this->pubInterview)) {
            $results = $this->pubOtherListing("PublicityInterview");
        }
        $this->pubInterview = $results;
        return $this->pubInterview;
    }
```
Otherwise, if $this->pubInterview is empty, PHP doesn't know which value to send to property $this->pubInterview

**Comment by duck7000** [comment]
Ah this is good spotted! thanks!

actually `$this->pubInterview = $results;` should have been inside the if statement..

The same is true for the other pub methods.

I'll change that

**Comment by duck7000** [comment]
This is fixed in latest commit

**Comment by jcvignoli** [comment]
Thanks, [your solution](https://github.com/duck7000/imdbGraphQLPHP/commit/b2fb131c258c6ba19c81e7f78e5062559da97ae8) is better indeed!

**Comment by duck7000** [comment]
I do listen to other users haha
