### ISSUE TITLE
incorrect phpdoc for Title::color() 

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#121]
Method Title::color() has a return phpdoc valule

`     * @return colors of array[0..n] of array[type, array attributes]`

it's missing the array declaration.

**Comment by duck7000** [comment]
Fixed in latest commit for color, camera, sound and ratio
Thanks!

**Comment by jcvignoli** [comment]
The fix is incorrect:

`* @return array $camerars of array[0..n] of array[cameras, array attributes]`
Here $camerars doesn't exist, but it's irrelevant anyway. Phpdoc should just end after the typeint, there is no need for a var. It should read as:

`* @return array array[0..n] of array[cameras, array attributes]`

same for the others, ie

`     * @return array array[0..n] of array[aspectRatio, array attributes]`

**Comment by duck7000** [comment]
very strictly to the point haha

Fixed in latest commit
