### ISSUE TITLE
add photoLocalurl() and savephoto() methods in Name class

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#126]
Based on Title class, whith a small difference: "nm{$this->imdbid()}" instead of "tt{$this->imdbid()}" variables in photoLocalurl() method.

```
    /**
     * Save the poster/cover image to disk
     * @param string $path where to store the file
     * @param boolean $thumb get the thumbnail or the
     *        bigger variant (max width 1000 pixels - FALSE)
     * @return boolean success
     * @see IMDB page / (TitlePage)
     */
    public function savephoto($path, $thumb = true)
    {
        $photoUrl = $this->photo($thumb);
        if (!$photoUrl) {
            return false;
        }

        $req = new Request($photoUrl, $this->config);
        $req->sendRequest();
        if (strpos($req->getResponseHeader("Content-Type"), 'image/jpeg') === 0 ||
            strpos($req->getResponseHeader("Content-Type"), 'image/gif') === 0 ||
            strpos($req->getResponseHeader("Content-Type"), 'image/bmp') === 0) {
            $image = $req->getResponseBody();
        } else {
            $ctype = $req->getResponseHeader("Content-Type");
            $this->debug_scalar("*photoerror* at " . __FILE__ . " line " . __LINE__ . ": " . $photo_url . ": Content Type is '$ctype'");
            if (substr($ctype, 0, 4) == 'text') {
                $this->debug_scalar("Details: <PRE>" . $req->getResponseBody() . "</PRE>\n");
            }
            return false;
        }

        $fp2 = fopen($path, "w");
        if (!$fp2) {
            $this->logger->warning("Failed to open [$path] for writing  at " . __FILE__ . " line " . __LINE__ . "...<BR>");
            return false;
        }
        fputs($fp2, $image);
        return true;
    }

    /** Get the URL for the movies cover image
     * @param boolean $thumb get the thumbnail (default) or the
     *        bigger variant (max width 1000 pixels - FALSE)
     * @return mixed url (string URL or FALSE if none)
     * @see IMDB page / (TitlePage)
     */
    public function photoLocalurl($thumb = true)
    {
        if ($thumb) {
            $ext = "";
        } else {
            $ext = "_big";
        }
        if (!is_dir($this->config->photoroot)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory does not exist!<BR>");
            return false;
        }
        $path = $this->config->photoroot . "nm{$this->imdbid()}" . "{$ext}.jpg";
        if (file_exists($path)) {
            return $this->config->photodir . "nm{$this->imdbid()}" . "{$ext}.jpg";
        }
        if (!is_writable($this->config->photoroot)) {
            $this->debug_scalar("<BR>***ERROR*** The configured image directory lacks write permission!<BR>");
            return false;
        }
        if ($this->savephoto($path, $thumb)) {
            return $this->config->photodir . "nm{$this->imdbid()}" . "{$ext}.jpg";
        }
        return false;
    }
```

**Comment by jcvignoli** [comment]
Commit https://github.com/duck7000/imdbGraphQLPHP/pull/127/commits

**Comment by duck7000** [comment]
This is looking good although i have one concern:

Images from both Title and Name class are saved in the same directory, this is not a direct concern as the images are separated with nm or tt of course.

But is it wise to save them each to a different directory?
Or is it just this way you or other users would want it to be?

Just a legit question

**Comment by duck7000** [comment]
those methods can be written more efficiently but for now it is fine.

The method from imdbphp Person class is even worse and/or weirder and contains a lot of issues so i'm glad you didn't use that one as base!

**Comment by jcvignoli** [comment]
> But is it wise to save them each to a different directory?

This is a legit question. But using a cache folder, with a images folder within. I have no issues. In my opinion, it's better to keep movies and people cache together. When cleaning the cache, it's easier to have multiple folders, but rather one for files and one for images.

> those methods can be written more efficiently but for now it is fine.

This core library of the library is 20 years old :) At some point we should move towards PHP8.0+ and refactorize a lot. There is indeed room for improvement.

> The method from imdbphp Person class is even worse and/or weirder and contains a lot of issues so i'm glad you didn't use that one as base!

If you're talking about savephoto() and photoLocalurl() methods, I copied-pasted from Title. But I guess you're refering to another method.

**Comment by duck7000** [comment]
> If you're talking about savephoto() and photoLocalurl() methods, I copied-pasted from Title. But I guess you're refering to another method.

The methods used in the old imdbphp from Tboothman, it is even worse, but that is nothing to worry about.

**Comment by duck7000** [comment]
I approved your PR and merge it so this can be closed
