### ISSUE TITLE
Added new method

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#54]
@GeorgeFive

I added a new method featuredReview, it will get (max 5) featured reviews of a title.
Info is in the wiki.
I'm not sure you will use it but it was missing and available. In imdbphp they called it comments but that is not the right name for this.

I also can add a method with more reviews (but that will max out at 50) so i don't know if that is of any use to anyone?

**Comment by GeorgeFive** [comment]
Hmmm.... I might play with this, let me think on it.  Could be useful...
