### ISSUE TITLE
Unable To Detect An Error Has Occurred Within GraphQL Request - imdbGraphQLPHP Exits With An Untrappable Error

### ISSUE THREAD

**Issue by mosource21** [duck7000/imdbGraphQLPHP#62]
<ins>Problem</ins>
If there is a problem with the GraphQL request (IMDB down, IMDB busy, DNS problem, Timeout etc) execution continues and many PHP warnings are output and eventually an PHP error is output (as the data imdbGraphQLPHP is expecting from the GraphQL request is not available) but you have no means of detecting that an error has occurred

<ins>Solution</ins>
Throw an exception in the GraphQL.php doRequest method so any calling code can trap this exception and act accordingly.  This is similar to what tboothman originally did but now simplified for your imdbGraphQLPHP implementation.

Change the following in GraphQL.php at line 100

Remove
`return new \StdClass();`

Replace With
`throw new \Exception("Failed to retrieve query [$queryName]");`

**Comment by duck7000** [comment]
Mm actually the logger is called in that case but yes logger has to be enabled in config to be able to see the error

Now that i think about this i never understood why you would need 2 different types of error reporting, but in this case when logger is disabled there is no way to see any errors.

If i implant your solution it will but the ordinary user will see a exception error but doesn't know/understand what is going on?

And logger is in my view misleading as it does not actually "log" anything to a log file, it outputs an error to the browser.

So i'm not sure what the best solution is?

**Comment by duck7000** [comment]
After some reading how throw exceptions work i think there is indeed a flaw in doRequest.
If there is any error or things go wrong the script continues with a blank object, this can work but is obviously not the best solution as there is no point continuing.
Best would be to break execution, and indeed throw exception is the best to do so.

So i think that re adding the exception classes:
require_once __DIR__ . '/src/Imdb/Exception.php';
require_once __DIR__ . '/src/Imdb/Exception/Http.php'; 

And adding your solution (or what tboothman did?)
Would a config option be necessary? or always true? I think that is not the right way as a user can disable this, keeping the same problem.

**Comment by duck7000** [comment]
Thanks for your explanation

Okay i'll implant your solution as it is indeed a simple fix.

thanks for checking my code, I'll appreciate it!

**Comment by duck7000** [comment]
fixed in latest commit

**Comment by mosource21** [comment]
Yes both commits looking good.  Timeout and throwing error now working great.  Many thanks for including the changes.

**Comment by duck7000** [comment]
thanks for testing!
