### ISSUE TITLE
Suggestion: Add a cover image in the award() section of Name to return it

### ISSUE THREAD

**Issue by jianglin8-hub** [duck7000/imdbGraphQLPHP#68]
When obtaining artist information, it is hoped that relevant artwork poster images can be returned at the same time, which is very useful for artist introductions.

For example, the list of works returned by award currently has an IMDB ID. If you need to display pictures of your works, you need to query the information of your works again, which seems too cumbersome.

**Comment by jianglin8-hub** [comment]
> I'm not sure i understand what you exactly mean?
> 
> Do you want to add image url to this section of award()
> 
> ```
>                 //credited titles
>                 $titles = array();
>                 if ($edge->node->awardedEntities->secondaryAwardTitles !== null) {
>                     foreach ($edge->node->awardedEntities->secondaryAwardTitles as $title) {
>                         $titleName = isset($title->title->titleText->text) ? $title->title->titleText->text : '';
>                         $titleId = isset($title->title->id) ? $title->title->id : '';
>                         $titleNote = isset($title->note->plainText) ? $title->note->plainText : '';
>                         $titles[] = array(
>                             'titleId' => str_replace('tt', '', $titleId),
>                             'titleName' => $titleName,
>                             'titleNote' => trim($titleNote, " ()")
>                         );
>                     }
>                 }
> ```

Yes, I need a photo of the imdb ID

**Comment by duck7000** [comment]
Okay i'll see what i can come up with
Do you want the full image url or a thumbnail?
If thumbnail what size you prefer?

**Comment by jianglin8-hub** [comment]
> Okay i'll see what i can come up with Do you want the full image url or a thumbnail? If thumbnail what size you prefer?

Well, can we add them all?

**Comment by duck7000** [comment]
No, impossible
imdb works with parameters in the url so you can get thumbnail in any size or the full image url
The full image url is the easiest (and largest!), you can use it to get the image and resize it yourself if you want.

For display purpose thumbnail would be sufficient i guess

**Comment by jianglin8-hub** [comment]
> No, impossible imdb works with parameters in the url so you can get thumbnail in any size or the full image url The full image url is the easiest (and largest!), you can use it to get the image and resize it yourself if you want.
> 
> For display purpose thumbnail would be sufficient i guess

It's also possible, at least there are pictures available

**Comment by duck7000** [comment]
This is added in the latest commit version

**Comment by jianglin8-hub** [comment]
salary
pubprints
pubmovies
creditKnownFor
credit

Can these also be added?

**Comment by duck7000** [comment]
I don't understand what you are asking as all those methods are already there?

**Comment by duck7000** [comment]
Salary, pubprints and pubmovies don't have images (if that is what you mean)
credit and creditknownfor do have images, i'll look in to that (if that is what you mean)

You need to be more specific when asking something, this is way too short to understand what you are exactly asking

**Comment by jianglin8-hub** [comment]
> Salary, pubprints and pubmovies don't have images (if that is what you mean) credit and creditknownfor do have images, i'll look in to that (if that is what you mean)
> 
> You need to be more specific when asking something, this is way too short to understand what you are exactly asking

Same as award, add the picture

**Comment by duck7000** [comment]
Okay i understand but you still don't listen to what i said.

Again: salary, pubprint and pubmovies DON'T have images. (Unless you can proof otherwise?)
So i can only add credit and creditkownfor, i'll see what i can do

**Comment by jianglin8-hub** [comment]
> salary

<img width="819" alt="image" src="https://github.com/duck7000/imdbGraphQLPHP/assets/16495257/84c01a81-9914-42f5-9fa0-01c8dceb21b0">

I'm not sure which methods have cover pages. I saw a query for title in salary, so I guess that has a cover page as well.

**Comment by duck7000** [comment]
> > salary
> 
> <img alt="image" width="819" src="https://private-user-images.githubusercontent.com/16495257/347334247-84c01a81-9914-42f5-9fa0-01c8dceb21b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDI1NjgsIm5iZiI6MTcyMDYwMjI2OCwicGF0aCI6Ii8xNjQ5NTI1Ny8zNDczMzQyNDctODRjMDFhODEtOTkxNC00MmY1LTlmYTAtMDFjOGRjZWIyMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Njk0MmZjZDM4YWViOWU5NWNiYmQ2OTAzZGZiMzQ3OGY1NGY3MjAwM2E4ZTA0Y2U5ZDk2OWM5NzhiM2ViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uOQf0xGfrKx6u_orzczB0GTkithLnlqQaqefWjWtMNI">
> 
> I'm not sure which methods have cover pages. I saw a query for title in salary, so I guess that has a cover page as well.

Ah now i understand why you come up with salary but no not every method that has title in their query has images.

So i will add images to credit and creditknowfor as i know for sure that those methods do have images

**Comment by jianglin8-hub** [comment]
> > > salary
> > 
> > 
> > <img alt="image" width="819" src="https://private-user-images.githubusercontent.com/16495257/347334247-84c01a81-9914-42f5-9fa0-01c8dceb21b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDI1NjgsIm5iZiI6MTcyMDYwMjI2OCwicGF0aCI6Ii8xNjQ5NTI1Ny8zNDczMzQyNDctODRjMDFhODEtOTkxNC00MmY1LTlmYTAtMDFjOGRjZWIyMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Njk0MmZjZDM4YWViOWU5NWNiYmQ2OTAzZGZiMzQ3OGY1NGY3MjAwM2E4ZTA0Y2U5ZDk2OWM5NzhiM2ViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uOQf0xGfrKx6u_orzczB0GTkithLnlqQaqefWjWtMNI">
> > I'm not sure which methods have cover pages. I saw a query for title in salary, so I guess that has a cover page as well.
> 
> Ah now i understand why you come up with salary but no not every method that has title in their query has images.
> 
> So i will add images to credit and creditknowfor as i know for sure that those methods do have images

Thanks!

**Comment by duck7000** [comment]
credit and creditKnownFor images are now added in latest git commit

**Comment by jianglin8-hub** [comment]
The salary method should also have a primaryImage, for example: https://www.imdb.com/name/nm0005562/bio/

**Comment by duck7000** [comment]
Well salary and pubmovies technically don't have images (imdb don't list them) but the url to the title technically does have a primaryImage.

I think that the images don't add anything to those methods? For example salary is about what the actor is earning for this title not for the title itself.
So i think this is going too far beyond what the method is about.

credit and creditKnownFor do list the images so they add something

**Comment by jianglin8-hub** [comment]
> Well salary and pubmovies technically don't have images (imdb don't list them) but the url to the title technically does have a primaryImage.
> 
> I think that the images don't add anything to those methods? For example salary is about what the actor is earning for this title not for the title itself. So i think this is going too far beyond what the method is about.
> 
> credit and creditKnownFor do list the images so they add something

Maybe the data that is related is a movie, um. It doesn't seem necessary, let's put it aside for now.

Thank you.

**Comment by duck7000** [comment]
Thanks for understanding my decision
