### ISSUE TITLE
movies_director() and movies_actor()

### ISSUE THREAD

**Issue by jcvignoli** [duck7000/imdbGraphQLPHP#75]
Hi,

With the old IMPhp, I used to use movies_director() and movies_actor() methods in Person.php.

I can't find a similar way to extract director and actor movies for a given person in Name class.

Could you direct me how to achieve it?

Thanks.

**Comment by duck7000** [comment]
In the Name class there is a method called credit()
This method contains all credits for this person including actor/actress and director.

There are no separate methods for director or actor as nobody asked for this or seems to need it.

The method creditKnownFor() does do the same as credit() but only for most known for movies where this person appeared as actor or director etc.

Let me know if this enough for you or if you have different ideas?

**Comment by jcvignoli** [comment]
Thanks a million @duck7000 ! Using credit() method allowed me to find my way :)
