### ISSUE TITLE
keyword() - PHP warning:  Attempt to read property "text" on null in Title.php on line 1930 

### ISSUE THREAD

**Issue by mosource21** [duck7000/imdbGraphQLPHP#78]
When accessing keyword() depending on data retrieved from IMDB the following PHP warning can be displayed (using PHP 8.1).

PHP Warning:  Attempt to read property "text" on null in /src/Imdb/Title.php on line 1930

`$this->keywords[] = $edge->node->keyword->text->text;`

I fixed with:

`if (!empty($edge->node->keyword->text->text)) { $this->keywords[] = $edge->node->keyword->text->text; }`

Thanks

**Comment by duck7000** [comment]
I fixed this in latest git commit.
Made a check if $data is empty or not

Can you test if this is sufficient?

**Comment by mosource21** [comment]
> Made a check if $data is empty or not
> Can you test if this is sufficient?

It is a great change and certainly good practice but unfortunately not sufficient for this specific case. 

I have tried few entries with no keywords and I didn't get any errors either with the old code.  

> Can you give me an example movie?

Apologies I didn't get back sooner I was exhausted and called it a day yesterday and didn't notice your request for more information.

IIRC tt5884796 there were approximately 150 keywords and one of them was null/empty and this caused the warning.

The code I posted above sorted the problem for me but not sure if it matches your usual coding style.

Thanks

**Comment by duck7000** [comment]
Mm with tt5884796 i get all 166 keywords, with or without my extra check, without any errors?

I think this has something to do with imdb somehow but i will add a extra check if the keyword value is empty to be sure. That will also mean there might be keywords missing, i can't do anything about that.

**Comment by duck7000** [comment]
This is fixed in latest commit.

Can you test if this works for you?

Still weird behavior though, it doesn't happen to me here in the Netherlands

**Comment by mosource21** [comment]
> Mm with tt5884796 i get all 166 keywords, with or without my extra check, without any errors?

Strange I get 167 keywords which includes a null/blank entry.  

> Can you test if this works for you?

Working perfectly now - thanks.  166 keywords and no null/blank entry being included.

> Still weird behavior though, it doesn't happen to me here in the Netherlands It seems to me that keywords are cut off at 150 at your end somehow?

The 150 was purely an approximation - I didn't have access to the PC.  All I can think of it is a PHP difference (unlikely I think as it is only processing the data it receives) or more than likely a wierd localization issue of the data being sent back from IMDB.

Thanks again.

**Comment by duck7000** [comment]
Well i'm glad it is fixed now.

Can you test if this happens to other methods? I never have seen this behavior before.
Maybe i need to add those checks to other methods as well?

**Comment by mosource21** [comment]
I have not experienced this with any other methods I have used but as it may be data related adding additional checks may be good practice at least just before the foreach statements (as you have already done for a few others).  

On more specific fields if it is a similar simple method as keyword there may be a benefit but unless there is a known problem I think it would just make the code unnecessarily harder to read and no changes should be made.

A few comments to consider (note I am not really that familiar with the whole data and down to personal preference:

>if (isset($edge->node->keyword->text->text) && !empty($edge->node->keyword->text->text)) {

I am not sure what benefit checking isset and !empty is.  I usually just use the !empty() check as if the variable is not set the !empty would cover that check anyway apart from a few edge cases which I do not think apply?  A valid keyword would never be 0(int) or FALSE(bool).

>if ($data != null) {
>if (isset($edge->node->primaryImage->url) && $edge->node->primaryImage->url != null) {
>if ($data->title->countriesOfOrigin != null) {
>et al

I prefer the tidyness of using !empty($data), !empty($edge->node->primaryImage->url) and !empty($data->title->countriesOfOrigin) instead of the above.  

As already stated the only time !empty() needs to be used with care is if any of the actual values can actually be 0(int) or FALSE(bool) and !empty would cause these values to be wrongly skipped.  

If $data was 0(int) of FALSE(bool) I think it should still be skipped, if url was 0(int) of FALSE(bool) that wouldn't be an url and should be skipped and if countriesOfOrigin was was 0(int) of FALSE(bool) that would not be a valid and should be skipped.

**Comment by mosource21** [comment]
I have looked at the commits and at first glance they seem fine.  I will report back in a few days once I have time to actually run them.  Thanks

**Comment by mosource21** [comment]
> I have adjusted Title and Name classes to use !empty() where possible

I do not use quite a few bits directly but it seems fine.  
A few pointers below.  Hope they are of some use.
I have removed quite a few I had listed as you fixed many yourself over the past few days.

<ins>Title.php</ins>
Line 2519: if (!empty($edge->node->countries) && !empty($edge->node->countries[0]->text)) {
I think just !empty($edge->node->countries[0]->text) should be adequate
Line 2519: if (!empty($edge->node->countries[0]->text)) {

Line 2529: if (!empty($edge->node->yearsInvolved) && !empty($edge->node->yearsInvolved->year)) {
I think just !empty($edge->node->yearsInvolved->year) should be adequate
New Line 2529: if (!empty($edge->node->yearsInvolved->year)) {

<ins>Name.php</ins>
Line 480: if (!empty($data) && !empty($data->name->spouses)) {
I think just !empty($data->name->spouses) should be adequate
New Line 480: if (!empty($data->name->spouses)) {

Line 487: if (!empty($spouse->spouse->name)) {
Remove Line 487 it is not needed Line 488 should be adequate

> And concerning your original issue, can it be that caching has something to do with this? (if you use that of course)

Looks like the data is now fixed at IMDB.  Must have been a temporary issue.  The fix is still a worthwhile change as the library needs to be resilient to whatever data it receives.

**Comment by duck7000** [comment]
Thanks for your comments, i changed them in latest git.

Glad your issue is resolved and yes i'll keep the extra check. As a matter of fact i'm changing almost all methods to use that kind of checks just to be sure there are no useless errors.
I'm also refactoring a lot of methods to better data checks and output type to be correct (int cannot be null) so i changed those to -1 if there is no data.

**Comment by mosource21** [comment]
> output type to be correct (int cannot be null) so i changed those to -1 if there is no data.

Not really sure what you are trying to do here but could you use NULL and the is_null() function to check instead of using an arbitrary negative number? This page is useful to find out the differences between is_null/set/empty et al 
http://php.net/manual/en/types.comparisons.php - at end of the day just use what makes the more sense to you though!

Not sure if this is the correct wording but PHP isn't strongly typed so even though you are assigning different variable types to the same $test variable it doesn't cause any errors.

`$test=NULL;`
`var_dump($test);`
`$test=1;`
`var_dump($test);`
`$test="1";`
`var_dump($test);`
`$test=1;`
`var_dump($test);`
`$test=NULL;`
`var_dump($test);`

**Comment by duck7000** [comment]
Thanks for your comments!

The idea behind this is that PHP (from 8.0) is getting more type strict so i thought to make it more type correct.
That is something different then catch errors. I think i addressed al those errors to be fixed, but please report if you do find something.

Example:
If the output of a certain field from IMDb == int (like a year), what do i use if there is no data available?

1. null? This is not type correct to int (int cannot be null) and year cannot be null (can't be saved in MySQL int field)
2. 0? this is type correct but is not correct as there is no data so 0 wouldn't be representing no data?
3. -1 this is type correct to int but is not a valid year (year cannot be negative)? and negative numbers can only be saved to MySQL int if it is signed (field can be negative or positive numbers)

Those are problems that i did like to fix but it isn't easy.

Or do i discharge all my thoughts about be type correct and use NULL everywhere? It depends if those values are used to make calculations (or saving to database) then type correct is necessary, if it is for display purposes it don't matter.

So i'm happy to learn your thoughts about this!

**Comment by duck7000** [comment]
I made a new issue about this as your original question/issue here is solved.
