### ISSUE TITLE
thumnail width and height in settings?

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#79]
I'm thinking about moving all thumbnail width and height to config.
Now they all are fixed inside the methods and it isn't possible to set this if you want something else.

It can involve those methods in Title class:
photo()
recommendation()
cast()
episode()
mainphoto()

what is your opinion about this?
It can help if you want different thumbnail sizes but it can be annoying when there is a new version which override old settings

**Comment by GeorgeFive** [comment]
I do like how it's set up now, where I can call it from my script with the settings I desire, so I could get large images on cast and thumbnail on recommendations (for example), instead of one setting = one option.

Just moving the actual height and width settings over would be fine, I always check the config file when updating to make sure my old settings stay.

**Comment by duck7000** [comment]
> I do like how it's set up now, where I can call it from my script with the settings I desire, so I could get large images on cast and thumbnail on recommendations (for example), instead of one setting = one option.

I did like to know how you do that as cast() has no parameters so how can you change those fixed values inside the method?
That is the whole idea, bring those thumbnail settings to config so you can change sizes as you please.
Another option would be to add thumbnail size as parameter to the methods that have images

**Comment by GeorgeFive** [comment]
Ok, sounds good, just wanted to make sure I was totally clear on what you were proposing before I agreed, haha.  Yeah, that would definitely be helpful!

**Comment by duck7000** [comment]
The only difference will be that thumbnail width and height no longer set hard coded in the method but in config.
That way you can set any width or height you like for thumbnail.

The choice of large or thumbnail will remain of course, large image will remain what it is now, max 1000pixels to keep the size under control.

I noticed that, in English, i sometimes have a hard time to make it clear what i mean so sorry about that.

**Comment by duck7000** [comment]
@GeorgeFive 

I noticed 2 flaws/bugs in Name class photo()

1  the thumbnail ratio is not correct, the thumbnail image is almost square... I did choose at the time to not use the image calculation functions (in ImageFunctions class) for simplicity reasons but this was obviously a mistake.
IMDb uses 140x207 pixels as thumbnail size so my question is that acceptable for you?
i don't know if you even use the thumbnail in Name class.
If so i will adjust the method to use those image calculation functions (same as in Title class) and use 140x207 as the size.
The size is the same as recommendation()

2 If the thumbnail url is not found (404) then there is a fallback to return the full image url but that is not the max 1000 pixels version so it is possible in that case to get a huge image!
So i will adjust that to return max 1000 pixels image URL in that case, agree?

**Comment by duck7000** [comment]
All thumbnail image width and height are now in config in latest commit.
Except photo() in Name class (it needs work)

**Comment by GeorgeFive** [comment]
Sounds good, will check it out when I get home!

**Comment by duck7000** [comment]
Report any issues in #30
