### ISSUE TITLE
output from methods to be type correct or not?

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#80]
@mosource21
@GeorgeFive
@all 

I made some adjustments to try to get the output from methods to be type correct (like a year to be int from imdb) but the big question is how do i handle if there is no data?

The idea behind this is that PHP (from 8.0) is getting more type strict so i thought to make it more type correct.
That is something different then catch errors. I think i addressed al those errors to be fixed, but please report if you do find something.

Example:
If the output of a certain field from IMDb == int (like a year), what do i use if there is no data available?

1. null? This is not type correct to int (int cannot be null) and year cannot be null (can't be saved in MySQL int field)
2. 0? this is type correct but is not correct as there is no data so 0 wouldn't be representing no data?
3. -1 this is type correct to int but is not a valid year (year cannot be negative)? and negative numbers can only be saved to MySQL int if it is signed (field can be negative or positive numbers)

Those are problems that i did like to fix but it isn't easy.

Or do i discharge all my thoughts about be type correct and use NULL everywhere? It depends if those values are used to make calculations (or saving to database) then type correct is necessary, if it is for display purposes it don't matter.

So i'm happy to learn your thoughts about this!

_Originally posted by @duck7000 in https://github.com/duck7000/imdbGraphQLPHP/issues/78#issuecomment-2460487810_

**Comment by mosource21** [comment]
There is no perfect solution it all depends on your personal preference on what you want and how you want it to work.
I would not lose sleep trying to make the library perfect - it is impossible.
In my opinion perfection nearly always adds a lot of complexity and quite often for very little benefit.

> The idea behind this is that PHP (from 8.0) is getting more type strict so i thought to make it more type correct.

It is a big change if PHP is not allowing NULL to be assigned to variables.  
I have done no research but are you sure they are going to allow you to use a variable as integer only but not allow NULL to be assigned to it?

>If the output of a certain field from IMDb == int (like a year), what do i use if there is no data available?
>null? This is not type correct to int (int cannot be null) and year cannot be null (can't be saved in MySQL int field)

In MySQL when you define the field you configure to allow NULL or not.  
So a MySQL integer field ***can*** store a NULL (if you want).

>Or do i discharge all my thoughts about be type correct and use NULL everywhere? 
>It depends if those values are used to make calculations (or saving to database) 
>then type correct is necessary, if it is for display purposes it don't matter.

Refer to all of above but I prefer NULL and then more often or not you can use !empty to work with the data.

There are a few exceptions like when 0 is a valid value therefore empty(0)=TRUE so if the 0 was important it would be lost but generally this doesn't happen often it just needs to be considered depending on the context of the data being stored.

**Comment by duck7000** [comment]
Thanks for your comments, again!

You may be right, i'm overthinking this too much i guess.

And yes now you mentioned it integer field can indeed accept NULL if you set it, so that argument goes out the window.

So alright i'm going with NULL where possible and forget about type correctness. There will be at least one exception (year() will output 0 if there is no year (this has always be the case so i'll leave that alone).

**Comment by GeorgeFive** [comment]
I completely agree with @mosource21 on this one, but I will say, if you ever do proceed with this... can you keep a detailed list of what you changed so that we can update our own scripts?

**Comment by duck7000** [comment]
I already did proceeded..
Most changes won't affect users, only difference would be that if there is no data the output will be NULL instead of empty string. effectively this isn't a big change?

I adjusted the wiki pages accordingly, and there is  a whole list of commits with the changes.

I hope that that will be enough though

**Comment by GeorgeFive** [comment]
Ok, that is no big deal, that won't interfere.  I was worried about you changing something from NULL to 0, for example, which wouldn't work quite as well, hah.

**Comment by duck7000** [comment]
initially that was the plan but @mosource21 did advised against that.
I wanted to make the output type correct but in the end it doesn't really matter, so i decided to, where possible, if there is no data available the output would be null instead of empty strings.
Still there are some methods left with empty strings (like episodes) those methods works fine and are complex so i left that alone

**Comment by duck7000** [comment]
I did check all methods in Title class for changes that would cause issues and found none.
so closing this one
