### ISSUE TITLE
TitleSearchAdvanced class extended

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#82]
I added keywords constraint to this class.
Search can now include keyword or keywords

This is very handy to use in combination with the new keywordSearch, you can use the found keywords in TitleSearchAdvanced class to find all matching titles, imdb does do the same

I'll admit that this is only useful for niche keywords as search for sex or drugs will not get a good result.

Let me know if there are any issues with it, especially @GeorgeFive as the query is now longer

**Comment by GeorgeFive** [comment]
Haven't seen any issues so far, awesome!

**Comment by duck7000** [comment]
Nice, this one can of the list as well then
