### ISSUE TITLE
Bug - family / relatives

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbGraphQLPHP#86]
Affected classes:

$person->spouse()
$person->children()
$person->parents()
$person->relatives()

If a returned result does not have an imdb id, name is now returning null.

Example:

https://www.imdb.com/name/nm0000156/bio/

$person->relatives()

```Array
(
    [0] => Array
        (
            [imdb] => 0325364
            [name] => Pamela Goldblum
            [relType] => Sibling
        )

    [1] => Array
        (
            [imdb] => 
            [name] => 
            [relType] => Sibling
        )

    [2] => Array
        (
            [imdb] => 
            [name] => 
            [relType] => Sibling
        )

)```

**Comment by duck7000** [comment]
Mm this is a tricky one, i'll try to fix that

This is the raw output of relationName, watch what happens when there is no id

```
object(stdClass)#10 (2) {
  ["name"]=>
  object(stdClass)#8 (2) {
    ["id"]=>
    string(9) "nm0325364"
    ["nameText"]=>
    object(stdClass)#9 (1) {
      ["text"]=>
      string(15) "Pamela Goldblum"
    }
  }
  ["nameText"]=>
  NULL
}
object(stdClass)#14 (2) {
  ["name"]=>
  NULL
  ["nameText"]=>
  string(12) "Lee Goldblum"
}
object(stdClass)#18 (2) {
  ["name"]=>
  NULL
  ["nameText"]=>
  string(13) "Rick Goldblum"
}
```

**Comment by duck7000** [comment]
This is fixed in latest commit

Thanks for testing!

**Comment by GeorgeFive** [comment]
Thanks!

Sort of related.... I'm noticing that imdb lists a LOT of "Sibling (Sibling)" entries.  Like, they have info, but put "Sibling" instead of a name.

Example - https://www.imdb.com/name/nm0829880/bio/

If it was just one or two, I'd say ok, somebody submitted bad info.... but I could give you 727 imdb id's that are screwed up like that, and that's only "Sibling" (haven't checked Parent or Relative or or or or).

I know this isn't a class issue, but have you noticed this?

**Comment by GeorgeFive** [comment]
Final count on the above:

Sibling - 727
Parent - 390
Child - 558
Grandchild - 15
No Children - 640
Adopted Child - 4
Aunt or Uncle - 12
Cousin - 4
Grandparent - 33
Great Grandchild - 1
Great Grandparent - 2
Half Sibling - 43
Niece or Nephew - 26
Stepchild - 14
Stepparent - 3

This is just what I have in my database, so imdb obviously has more than this on their site.  Again, I know it's not a class issue, but it seems weird that there's so many of these.

**Comment by duck7000** [comment]
Mm i haven't notice this before but it is indeed very strange

what do they want to tell with "Sibling (sibling)" as the data from GraphQL looks like this (from your example)?
Do they want to tell that there are 2 siblings but unknown who it is?  

```
object(stdClass)#9 (2) {
  ["relationName"]=>
  object(stdClass)#8 (2) {
    ["name"]=>
    NULL
    ["nameText"]=>
    NULL
  }
  ["relationshipType"]=>
  object(stdClass)#10 (1) {
    ["text"]=>
    string(7) "Sibling"
  }
}
object(stdClass)#13 (2) {
  ["relationName"]=>
  object(stdClass)#12 (2) {
    ["name"]=>
    NULL
    ["nameText"]=>
    NULL
  }
  ["relationshipType"]=>
  object(stdClass)#14 (1) {
    ["text"]=>
    string(7) "Sibling"
  }
}
```
Only relationshipType has a value but no name or id?
I think we can exclude this kind of "information" as it has no value?

I need an example of each of your list to test

**Comment by duck7000** [comment]
I added a fix to exclude object name and nameText if they both are null.
So anything that only have a value for relationshipType is excluded as this has no real value

Can you test if this is enough?
In my quick tests it did

**Comment by GeorgeFive** [comment]
Just tested with a number of ids, all seems good.  Thanks!

**Comment by duck7000** [comment]
Glad to smash this bug as well, thanks for reporting and testing.
