### ISSUE TITLE
Request for Config.php setting for CURLOPT_TIMEOUT?

### ISSUE THREAD

**Issue by mosource21** [duck7000/imdbGraphQLPHP#89]
Is is possible to have the following line from Request.php to have its value set by a Config.php setting?

`curl_setopt($this->ch, CURLOPT_TIMEOUT, 30); (~line 38)`

If it was a setting in Config.php you could set the value in user code making things much easier and requiring no changes to the library code.

Thanks

**Comment by duck7000** [comment]
Mm why would you want to change that value?
30 seconds is the default php execution time so anything higher has no point, anything lower may cause to break too soon?
I'm just thinking out load, if you have a reason why this is important i'm all ears.

**Comment by mosource21** [comment]
I have it set to a much lower values.  This helps when there is a problem with connecting I am not waiting for multiple times x 30 seconds for the script to end.  

If you are using the CLI the default timeout is unlimited (not 30 seconds) so making it higher also has a very limited case - you would have to have a very poor connection for 30 seconds not to work through!

It is all personal preference - for me I would definitely use this option over other options but also appreciate you have to weigh up the pro's and con's of each request.

**Comment by duck7000** [comment]
Good point! i was already in doubt with the name but since it works i left it like it is.
I will change that of course

**Comment by duck7000** [comment]
This is fixed in latest commit.
Thanks for testing!

**Comment by mosource21** [comment]
Working great.  Thanks again.  Issue can be closed.
