### ISSUE TITLE
Calendar Class added comingSoonStreaming

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#90]
@GeorgeFive
@All

I added this method to Calendar Class

It gets steaming releases from big providers of the current month like seen on this page:
https://www.imdb.com/list/ls549391228/ (Netflix)
I'm not sure how often this will be updated but those are lists from IMDb Editors so it is likely updated frequently

All info is in the wiki, i didn't find more streaming providers (like AMC+ or Apple TV+) those don't have own lists so if you want those use the common option at the bottom of the providerId's

Test it out if you like and let me know how it works.
Please report any Suggestions and bugs here

**Comment by GeorgeFive** [comment]
Seems like a pretty cool idea (streaming availability is BIG on my wishlist!!), but if I'm understanding this right, this list is only good for November... right?  So next month, I would have to dig around and find the new lists (if available), and then change the ids in my own app to reflect this?

**Comment by duck7000** [comment]
I don't think that it work like that, the listid will stay the same (AFAIK).
The list maintainer (an imdb editor) will update the list for next month.

I'm not 100% certain but we will see how it act next month.

**Comment by GeorgeFive** [comment]
I just went to check something, and the December list for Netflix has been added:

https://www.imdb.com/list/ls548902643/

Seems it will indeed have to be rotated.

**Comment by GeorgeFive** [comment]
Go to the list of their lists from the Netflix link you posted up above (click the IMDb-Editors username):

https://www.imdb.com/user/ur23892615/lists

If you scroll a bit, you'll see the old October list in there as well.

I'm not sure I'd say useless, because this is functionality I'd love to have (maybe even a list of all Netflix/Paramount/Amazon/etc movies)... I think we just need to figure out a better way.

**Comment by duck7000** [comment]
Through lists is not the way apparently, but what i made can be used to list all titles of specific list id so no it is not totally useless but useless for the goal of getting streaming info.

So still no real option to get streaming info..

**Comment by duck7000** [comment]
I was thinking about this..

what i (possible) can do is try to find a way to find all lists from https://www.imdb.com/user/ur23892615/ this user (the imdb-editors user that makes the streaming lists)

With the results we can pick the listid we want and use that in comingSoonStreaming?
So kind like a search but for a specific user

I am going to give this idea a go

**Comment by duck7000** [comment]
Well... i tried but nothing seems to work.

I get forbidden, bad user input etc and the functions that does seems to be related to user don't work or don't give any list in return, although they do have a option for that but if you go deeper there are only options for Title, Name, Image etc but not for list or lists

so again a massive dead end i'm afraid

The only thing you can do is check the imdb-editors user page and get the ls id's from there

**Comment by duck7000** [comment]
Other (in my view near useless) is this:

watchOptionsByCategory function in GraphQL, it will get available watch options for a specific title. I hear you thinking, this is it! but don't get your hopes up jet.
It can only return streaming providers from IMDb (Amazon) so it can return Amazon Prime or nothing

So useless to get all streaming providers for a specific title but it can list Amazon prime

I don't think this will get you any further in the search for streaming info

**Comment by GeorgeFive** [comment]
Damn... that sounds like it would have been perfect, if it did more than just Amazon.  Maybe this is outsourced info on their end?  I know there's a few sites that provide this data, but it costs money (and isn't cheap).

**Comment by duck7000** [comment]
Jep i know, another dead end, I will leaf it at this as there is no other alternative left, at least not on imdb
