### ISSUE TITLE
Any interest in News or topBoxoffice?

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#91]
news https://www.imdb.com/news/movie/
It can be for movie, tv, name, top or indie

topBoxOffice https://www.imdb.com/chart/boxoffice/

I have the querys for both but i'm not sure if anyone will ever use it though.
I can add it anyway of course

**Comment by GeorgeFive** [comment]
I probably wouldn't use them, but they are definitely neat to have.  I have my own box office system set up, but if I didn't have that already, I would have used this.

**Comment by duck7000** [comment]
Okay i will add this, it doesn't really matter if anyone is using it but it won't be tested by users is my concern

**Comment by duck7000** [comment]
This is added in latest git commit
