### ISSUE TITLE
Add Parents guide

### ISSUE THREAD

**Issue by lunoxis** [duck7000/imdbGraphQLPHP#92]
Hello, is it possible to add the parent's guide along with its complete details?

https://www.imdb.com/title/tt13818368/parentalguide/?ref_=tt_stry_pg
example

**Comment by duck7000** [comment]
Well that should be possible i suppose, i'll investigate it.
Nobody ever asked for this, that's why it was never added.

**Comment by lunoxis** [comment]
I think this option is very useful
thanks

**Comment by duck7000** [comment]
I added this method in the latest commit

check it out and please report back how it works.
If you have any issue/bugs with this method let me know

**Comment by mosource21** [comment]
Came across these whilst testing other things hopefully it helps.

#### Warning: Undefined variable $spoiler in /src/Imdb/Title.php on line 744:

<ins>Change (Line ~744)</ins>
`if ($spoiler === false) {`

<ins>To (Line ~744)</ins>
`if ($spoil === false) {`

#### Minor typo:

<ins>Change (Line ~737)</ins>
`* [isSpoiler] => (boolean) (true: include spoilers, false: exclude spoilers)`

<ins>To (Line ~737)</ins>
`* [isSpoiler] => (boolean) (indicates if entry is a spoiler or not)`

**Comment by duck7000** [comment]
@mosource21 
thanks for testing!, late night bugs i suppose hah
Those are fixed in latest commit, updated wiki page as well
