### ISSUE TITLE
ReWrote TitleSearchAdvanced

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#96]
@GeorgeFive

I reWrote this class just like i added NameSearchAdvanced and those are the changes:

1. The input parameters $creditId and $companyId are now without the leading letters ($creditid without "nm", $companyId without "co") to be compliant with all other id's
2. Added thumbnail support, width and height are set in config.
3. ReWrote the whole constraints part (just like NameSearchAdvanced) form now constaints are only included if they have a valid parameter, otherwise they are not included.

With those changes, especially the constraints part, it will be much easier to add more constraints and it limits the query to what is absolutely necessary.

This is NOT in git jet because i would like you to test it before i add it, so would you be so kind to do so?
[Imdb.tar.gz](https://github.com/user-attachments/files/17965964/Imdb.tar.gz)
Make sure you made a copy of TitleSearchAdvanced and config before overriding
It should work without any changes on your side, unless you use $creditId or $companyId

Edit: this is implanted

**Comment by duck7000** [comment]
Thanks for testing!

I will implant this in the coming days.

If you or anybody else want more constraints let me know as it is now possible

**Comment by duck7000** [comment]
This is now in latest git commit.

Any issues or requests report here please

**Comment by GeorgeFive** [comment]
Ok, one thing I just noticed.... searching by top movies by genre seems to only return top movies, period.  I'm doing:

        $genres = array("Action", "Adult", "Adventure", "Animation", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "History", "Horror", "Music", "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Thriller", "War", "Western");
        $movies = new \Imdb\TitleSearchAdvanced();
    foreach ($genres as $genre) {
        $results = $movies->advancedSearch("", $genre);

This returns a list of popular movies that seems about right, but genre is ignored.  For each genre, I get the same list of movies:

Gladiator II
Arcane
Dune: Prophecy
How to Train Your Dragon
Cross
Cobra Kai
Gladiator

etc etc.  But I'm getting the exact same list for each genre.  Oddly, the results they provide don't line up with what they have on the site anywhere.

Reverting to the previous version does fix this, so I'm not sure if the "" is affecting it now?

**Comment by duck7000** [comment]
Mm this is strange

You mentioned top movies? this advanced search does not search by top movies, it just lists results based on on that genre sorted by populairity

My results are conform with what imdb gets as result if i add some genre at their site
If i add Action as genre then yes i get the same list as if i add Adventure as they all have that genre apparently
So in other words genres like Action, Crime and Drama are so common that they produce the same list

So technically it is working like imdb does but i got the feeling it has something to do with the first parameter been empty and thus the constraint is not added (just like imdb does on their site by the way)
So it might that in my previous version of TSA was a mistake/bug that accidentally give your results?
In the screenshot, bottom left you see the query that imdb uses if i only add Action as genre. My TSA does exactly the same.

![Screenshot_2024-12-01_20-05-20](https://github.com/user-attachments/assets/233a7614-aaab-4853-9e31-165fff88f4ef)

I reverted some check functions but that does not make a difference so the only thing that is different is titleTextConstraint not included

**Comment by duck7000** [comment]
What i can do (just found out) is add genreConstraint to mostPopularTitle method in Chart class?

It will get a list of most popular movies filtered by genre?

In fact all constraints that are possible for TSA can be used in this method as well

**Comment by duck7000** [comment]
I made it with the constraint and it works fine.
It can get Top rated and Popular movie or tv show, comingsoon is not possible

I will upload it asap

**Comment by GeorgeFive** [comment]
Yeah, I just pasted a very brief example, I do more stuff with the data inside the foreach and then save it to my db for processing.

Let me check your update and see what that does before I type more, hahaha.

**Comment by GeorgeFive** [comment]
Ok, so I've updated my code to use chart.... still getting basically the same thing.

Searching for "Horror", I get 96 results:

Gladiator II Action, Adventure, Drama
How to Train Your Dragon Action, Adventure, Comedy, Drama, Family, Fantasy
Gladiator Action, Adventure, Drama
Deadpool & Wolverine Action, Adventure, Comedy, Sci-Fi
Red One Action, Adventure, Comedy, Fantasy, Mystery

etc etc.  No horror in there...? Ok, so I search on the imploded genre (LIKE %Horror%) and I get only 18 results:

Ready or Not Action, Comedy, Horror, Mystery, Thriller
Apocalypse Z: The Beginning of the End Action, Horror, Sci-Fi, Thriller
Beetlejuice Beetlejuice Comedy, Fantasy, Horror
Y2K Comedy, Horror, Sci-Fi
Trap Crime, Horror, Mystery, Thriller
Heretic Horror, Thriller

Compare this to the old version, which returns 200 results for Horror:

From
The Substance
Heretic
Smile 2
Alien: Romulus
Terrifier 3
Stranger Things
The Walking Dead

Much more accurate there.  I think the key difference is that chart pulls the top 250 movies, and then searches inside those movies for the given genre.  May be useful to some, but not what I wanted.  The old version of TSA would grab the top 200 movies (by popularity) from the given genre.  You could even do adult on that and get proper results, every genre worked.

I think TSA was definitely much better for this!

**Comment by duck7000** [comment]
Mm if i use this i get 16 results, i don't understand how you would get 96? Ah that might be because i didn't include adult constraint, i will add that. Imdb gets 30 results on this page https://www.imdb.com/interest/in0000112/

```
$imdb = new \Imdb\Chart();
echo '<pre>';
    print_r($imdb->mostPopularTitle("MOST_POPULAR_MOVIES", "Horror"));
echo '/<pre>';
```
And TSA should not give you the results you get in the first place, i think this is a bug in the old version of TSA
I doubt that 200 items list is even accurate as it can't be in my view
The new TSA does exactly what it says on the tin and does exactly what imdb is doing so the old version must have a serious bug

**Comment by duck7000** [comment]
Okay  i tested a few different scenarios, all give the same results:

I renamed old TSA and tested like this
```
$imdb = new \Imdb\TitleSearchAdvanced_old();
echo '<pre>';
    print_r($imdb->advancedSearch("", "Horror"));
echo '/<pre>'; 
```

Then with the new tsa

```
$imdb = new \Imdb\TitleSearchAdvanced();
echo '<pre>';
    print_r($imdb->advancedSearch("", "Horror"));
echo '/<pre>';
```

Then with the search constaint added with null as value (same as the old TSA)
`$constraint .= 'titleTextConstraint:{searchTerm:null}';`

```
$imdb = new \Imdb\TitleSearchAdvanced();
echo '<pre>';
    print_r($imdb->advancedSearch("", "Horror"));
echo '/<pre>';
```

Again all those test gives the same 250 items list so i really don't know what to say

**Comment by duck7000** [comment]
I tested the above with Comedy and again the results are the same for all 3 tests.

And they are different then the tests with "Horror" and accurate according to TSA on imdb

So i'm flabbergasted so to speak because i don't understand why it works differently at your end?

**Comment by GeorgeFive** [comment]
OK!  I figured out the difference.

In my script, I am trying to go through all genres and get the most popular 200 movies for each.  So, top 200 for Action, top 200 for Adventure, Adult, Comedy, etc etc.

The problem was that $results wasn't resetting after each loop of the foreach... even though I used unset($results) at the end of each loop.  Calling the class inside the foreach actually fixes it, even though this worked in the old TSA.

        $genres = array("Action", "Adult", "Adventure", "Animation", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "History", "Horror", "Music", "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Thriller", "War", "Western");
        $movies = new \Imdb\TitleSearchAdvanced();
    foreach ($genres as $genre) {
        $results = $movies->advancedSearch("", $genre);

^Does not work, gives us the problems I've been mentioning (worked properly in old TSA though)

        $genres = array("Action", "Adult", "Adventure", "Animation", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "History", "Horror", "Music", "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Thriller", "War", "Western");
    foreach ($genres as $genre) {
        $movies = new \Imdb\TitleSearchAdvanced();
        $results = $movies->advancedSearch("", $genre);

^Works as expected!

**Comment by duck7000** [comment]
Ah i added __construct() to the new TSA (this way the results can be cached and was mentioned by another user), that might explain the difference but i still don't see why that should/could be of influence of the outcome of the method inside the class?

**Oooh** i see what the problem is now... and you are right (i'm a little embarrassed!)
I added $results as a protected var at the begin of the class... so that is why it doesn't work the same as the old version of TSA.
With every call of TSA class this protected var will be reset.. explaining why that works fine

So what is the best solution?
I never assumed/thought about that if you call the class once and re use a method inside it it never resets the protected var.
I can reverse that change to old TSA? 
Or you can keep it using like it is now but that is not very efficient to call the class over and over again

**Comment by duck7000** [comment]
I reverted the protected var to the old TSA, it should now work like old TSA
It is in latest git commit

I will revert other classes as well to prevent this kind of issues.
I just thought it would be a good idea but it is not.

**Comment by GeorgeFive** [comment]
All good!  I updated everything from git and then overwrote TSA with your test file here, and everything works as expected.  Thanks!

And don't ever worry about going too fast... I've recently got a promotion at work which requires me to be on site a lot longer, but even though I have less time, I'll still catch up when I can, haha.

**Comment by duck7000** [comment]
Thanks for testing, i will add this new test TSA asap

Haha your are just like me, no matter what still going on
