### ISSUE TITLE
Name class credit() and creditKnownFor() changes

### ISSUE THREAD

**Issue by duck7000** [duck7000/imdbGraphQLPHP#98]
1. Both methods use now thumbnail functions from Image class
2. Both methods thumbnail size is changed to 140x20 (Fixed) to better suit other thumbnail sizes

**Comment by GeorgeFive** [comment]
I've never played with creditKnownFor... just out of curiosity, do you know the logic that they use to determine which titles to show here?

**Comment by duck7000** [comment]
CreditKnownFor will get the most known credits, credit will get all credits

No i don't no how they determine what is most in their view but on every name page they are listed
https://www.imdb.com/name/nm0001228/#knownFor

**Comment by GeorgeFive** [comment]
Gotcha... yeah, I saw the data on their end, but never really thought about how it's determined.  I don't really see a logic to how they determine which movies to show, but they do seem like pretty good picks, even for lesser known people.

Stupid question, but I haven't touched the code yet... can this show more than just the four titles that are displayed on their site?

**Comment by duck7000** [comment]
Sure, i get 20 results with the above example.
This will depend on how well known a person is i guess, but i suspect that this won't be more then 100.
If you want more use credit() to get all credits

**Comment by GeorgeFive** [comment]
Ok, this should be pretty good for my use case, then.  I was mainly concerned with... if a person has 4x "known for" items, but maybe I don't have 1 of them in my database, skip over that one and get the next.... so even with one missing, we'll still theoretically get 4.
